### ISSUE TITLE
Stream starves in browser environment

### ISSUE THREAD

**Issue by ktk** [zazuko/sparql-http-client#35] opened 2021-09-27 12:10 UTC

**Comment by ktk** [comment] 2021-11-29 15:10
@BenjaminHofstetter this was Angular related, is this still relevant or can we close that? Not sure we can even do something on our side.

**Comment by BenjaminHofstetter** [comment] 2021-11-30 21:35
You can close it. The problem is related to this https://github.com/angular/angular/issues/31730

**Closed** 2021-11-30 21:36 UTC
